name: Code coverage
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test -- --coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
